-- rxqAgency   (58 rows, 42 columns)
-- Source: RXQRXCOMPOUNDSTORE (Liberty). Read-only reference DDL, synthesized from catalog metadata.
CREATE TABLE [dbo].[rxqAgency] (
    [AgencyCode] varchar(50) NOT NULL,
    [AgencyDescription] varchar(50) NULL,
    [ProviderIdSource] int NOT NULL,
    [BIN] int NOT NULL,
    [PCN] varchar(50) NOT NULL,
    [PriceFormulaCode] varchar(50) NOT NULL,
    [WorkersCompSwitch] varchar(50) NULL,
    [PrescriptionScreenDisplay] varchar(500) NULL,
    [MaxScriptsPerMonth] int NULL,
    [WelfarePriceType] varchar(50) NULL,
    [RefillsAllowed] int NULL,
    [DollarsAllowed] float NULL,
    [MonthsToRefillAllowed] int NULL,
    [NcpdpFormat] varchar(50) NULL,
    [PlanClassificationCode] char(2) NOT NULL,
    [UsualAndCustomaryOption] varchar(50) NULL,
    [LastUsed] date NULL,
    [ClaimsPerTransmission] int NULL,
    [DefaultOtherCoverageCode] char(2) NULL,
    [CompoundBillingNDC] varchar(50) NULL,
    [ReplacePaymentsWithUandC] bit NULL,
    [OverrideNcpdpPharmacyServiceType] char(2) NULL,
    [LastModified] datetime NULL,
    [IsValid] bit NULL,
    [DirFeeId] varchar(50) NULL,
    [InActive] bit NULL,
    [PercentageTaxExempt] bit NOT NULL,
    [FlatTaxExempt] bit NOT NULL,
    [DefaultBasisOfCost] nvarchar(2) NULL,
    [DefaultSubClarificationCode] varchar(200) NULL,
    [MedicareCarrierNumber] nvarchar(50) NULL,
    [Is340B] bit NULL,
    [BillImmunization] int NULL,
    [SubmitCompoundsMode] int NULL,
    [UsualAndCustomaryCustomPF] varchar(200) NULL,
    [RejectionPF] varchar(200) NULL,
    [IncludeLoyaltyPriceInUC] varchar(50) NULL,
    [GerGroupId] int NULL,
    [IsDiscount] bit NOT NULL,
    [AllowFormulaOnCOB] bit NOT NULL,
    [CustomField1] varchar(50) NULL,
    [CustomField2] varchar(50) NULL,
    CONSTRAINT [PK_rxqAgency] PRIMARY KEY ([AgencyCode])
);
