-- rxqChangeLogEntry   (1,471,629 rows, 127 columns)
-- Source: RXQRXCOMPOUNDSTORE (Liberty). Read-only reference DDL, synthesized from catalog metadata.
CREATE TABLE [dbo].[rxqChangeLogEntry] (
    [cChangeLogEntryId] int IDENTITY NOT NULL,
    [ScriptNumber] int NOT NULL,
    [RefillNumber] int NOT NULL,
    [ChangeDate] datetime NOT NULL,
    [PharmacistInitials] varchar(50) NULL,
    [LoggedInUser] varchar(50) NULL,
    [ChangeDescription] varchar(200) NULL,
    [TypeCode] varchar(50) NULL,
    [BaseScriptNumber] int NULL,
    [BaseLastRefillNumber] int NULL,
    [PatientId] varchar(50) NULL,
    [BaseDrugKey] varchar(50) NULL,
    [BaseDrugSchedule] varchar(50) NULL,
    [BaseDateWritten] date NULL,
    [BaseDateLastFilled1] date NULL,
    [BaseDateLastFilled2] date NULL,
    [BaseDateLastFilled3] date NULL,
    [BaseDateLastFilled4] date NULL,
    [BaseDoctorId] varchar(50) NULL,
    [BaseFullDispenseQuantity] varchar(50) NULL,
    [BaseAuthorizedQuantity] varchar(50) NULL,
    [BaseAvailableQuantity] varchar(50) NULL,
    [BaseRefillsAuthorized] int NULL,
    [BaseNumberOfLabels] int NULL,
    [BaseScriptStatus] int NULL,
    [BaseStoreNumber] varchar(50) NULL,
    [BaseCvtFrom] int NULL,
    [BaseInjuryDate] date NULL,
    [BaseOnHold] varchar(50) NULL,
    [BaseTransferSwitch] varchar(50) NULL,
    [BaseRefillUntilDate] date NULL,
    [BaseEScriptTransactionId] int NULL,
    [TransAdministrativeCharge] varchar(50) NULL,
    [TransAgency] varchar(50) NULL,
    [TransAuthorizationNumber] varchar(50) NULL,
    [TransAuthorizedBy] varchar(50) NULL,
    [TransChargeCode] varchar(50) NULL,
    [TransCopay] varchar(50) NULL,
    [TransCost] varchar(50) NULL,
    [TransCostBase] varchar(50) NULL,
    [TransCountedByUser] varchar(50) NULL,
    [TransCouponAmount] varchar(50) NULL,
    [TransCouponNumber] varchar(50) NULL,
    [TransCouponType] varchar(50) NULL,
    [TransCpt1] varchar(50) NULL,
    [TransCpt2] varchar(50) NULL,
    [TransDateDispensed] date NULL,
    [TransDaysSupply] varchar(50) NULL,
    [TransDeliveryCharge] varchar(50) NULL,
    [TransDenialClarification] varchar(50) NULL,
    [TransDiagnosisCode] varchar(50) NULL,
    [TransDiscount] varchar(50) NULL,
    [TransDispenseAsWritten] varchar(50) NULL,
    [TransDrugId] varchar(50) NULL,
    [TransEmergencyCopayCode] varchar(50) NULL,
    [TransExpirationDate] date NULL,
    [TransFee] varchar(50) NULL,
    [TransIcd9Code] varchar(50) NULL,
    [TransLevelOfService] varchar(50) NULL,
    [TransLoggedInUser] varchar(50) NULL,
    [TransLotNumber] varchar(50) NULL,
    [TransNCPDCAmountDue] varchar(50) NULL,
    [TransNCPDCBasisOfCost] varchar(50) NULL,
    [TransNCPDCCustomerLocation] varchar(50) NULL,
    [TransNCPDCDenialClarification] varchar(50) NULL,
    [TransNCPDCDispenseAsWritten] varchar(50) NULL,
    [TransNCPDCDispensingFee] varchar(50) NULL,
    [TransNCPDCEligabilityClarification] varchar(50) NULL,
    [TransNCPDCGrossAmountDue] varchar(50) NULL,
    [TransNCPDCIngredientCost] varchar(50) NULL,
    [TransNCPDCLevelOfService] varchar(50) NULL,
    [TransNCPDCOtherPayorAmount] varchar(50) NULL,
    [TransNCPDCPatientPaidAmount] varchar(50) NULL,
    [TransNCPDCPriorAuthorizationCode] varchar(50) NULL,
    [TransNCPDCPriorAuthorizationNumber] varchar(50) NULL,
    [TransNCPDCSalesTax] varchar(50) NULL,
    [TransNCPDCUsualCustomaryCharge] varchar(50) NULL,
    [TransNewDateDone] date NULL,
    [TransNewScriptNumber] varchar(50) NULL,
    [TransNursingHome] varchar(50) NULL,
    [TransOtherCharge] varchar(50) NULL,
    [TransOtherCoverageCode] varchar(50) NULL,
    [TransPaidSwitch] varchar(50) NULL,
    [TransPaid] date NULL,
    [TransPcnNumber] varchar(50) NULL,
    [TransPosScanFlag] varchar(50) NULL,
    [TransPostageCharge] varchar(50) NULL,
    [TransPrescriptionOrigin] varchar(50) NULL,
    [TransPriceFormula] varchar(50) NULL,
    [TransPriceFormulaOriginal] varchar(50) NULL,
    [TransPrimaryPayorDenialDate] varchar(50) NULL,
    [TransPrimaryRejectedFlag] varchar(50) NULL,
    [TransQuantityDispensed] varchar(50) NULL,
    [TransReferenceNumber] varchar(50) NULL,
    [TransRefillNumber] varchar(50) NULL,
    [TransRequestedACQ] varchar(50) NULL,
    [TransRequestedAWP] varchar(50) NULL,
    [TransRequestedCON] varchar(50) NULL,
    [TransRequestedCopay] varchar(50) NULL,
    [TransRequestedDiscount] varchar(50) NULL,
    [TransRequestedFee] varchar(50) NULL,
    [TransRequestedTax] varchar(50) NULL,
    [TransRequestedTotal] varchar(50) NULL,
    [TransRphInitials] varchar(50) NULL,
    [TransRxFromNumber] varchar(50) NULL,
    [TransRxpIndicator] varchar(50) NULL,
    [TransScriptNumber] varchar(50) NULL,
    [TransShippingCharge] varchar(50) NULL,
    [TransSigs] nvarchar(500) NULL,
    [TransStoreNumber] varchar(50) NULL,
    [TransTax] varchar(50) NULL,
    [TransTimeStampComputerDate] datetime NULL,
    [TransTotal] varchar(50) NULL,
    [TransTriplicateSerialNumber] varchar(50) NULL,
    [TransUnitDoseIndicator] varchar(50) NULL,
    [TransUsualAndCustomary] varchar(50) NULL,
    [TransUsualAndCustomarySwitch] varchar(50) NULL,
    [TransWorkersCompFormType] varchar(50) NULL,
    [TransWorkFlowStatus] varchar(50) NULL,
    [LastModified] datetime NULL,
    [IsValid] bit NULL,
    [TransAgencySequence] int NOT NULL,
    [OverrideUser] varchar(50) NOT NULL,
    [TransStoreNumberInventory] varchar(50) NULL,
    [QuestionnaireReviewedDate] datetime NULL,
    [QuestionnaireReviewedBy] varchar(50) NULL,
    [LinkScriptNumber] int NULL,
    CONSTRAINT [PK_rxqChangeLogEntry] PRIMARY KEY ([ScriptNumber], [RefillNumber], [ChangeDate])
);

-- Indexes
CREATE INDEX [IDX_ChangeLog_TypeCodeChangeDate] ON [dbo].[rxqChangeLogEntry] ([TypeCode], [ChangeDate]) INCLUDE ([ScriptNumber], [RefillNumber], [TransStoreNumber]);
CREATE INDEX [IX_ScriptRefillChangeDateDescription] ON [dbo].[rxqChangeLogEntry] ([ScriptNumber], [RefillNumber], [ChangeDate], [ChangeDescription]);
CREATE INDEX [LibertyAuto_92_91_rxqChangeLogEntry] ON [dbo].[rxqChangeLogEntry] ([TransAgency]);
CREATE INDEX [LibertyAuto_94_93_rxqChangeLogEntry] ON [dbo].[rxqChangeLogEntry] ([TransAgencySequence]);
CREATE INDEX [RxqChangeLogEntry_FamilyIdentification] ON [dbo].[rxqChangeLogEntry] ([PatientId]);
