-- rxqDrug   (2,941 rows, 111 columns)
-- Source: RXQRXCOMPOUNDSTORE (Liberty). Read-only reference DDL, synthesized from catalog metadata.
-- NOTE: mirrored into liberty_link_stage by the eMed ETL.
CREATE TABLE [dbo].[rxqDrug] (
    [GID] numeric(18,0) IDENTITY NOT NULL,
    [DrugId] varchar(50) NOT NULL,
    [NdcNumber] varchar(50) NULL,
    [Strength] varchar(50) NULL,
    [Form] varchar(50) NULL,
    [Schedule] varchar(50) NULL,
    [Generic] varchar(50) NULL,
    [OverTheCounter] varchar(50) NULL,
    [StateCode] varchar(50) NULL,
    [Reorder] varchar(50) NULL,
    [Manufacturer] varchar(50) NULL,
    [ContainerCharge] varchar(50) NULL,
    [SpecialSwitch] varchar(50) NULL,
    [InventoryOption] varchar(50) NULL,
    [DrugCode] varchar(50) NULL,
    [Mixture] varchar(50) NULL,
    [PriceBreak] decimal(8,3) NULL,
    [Alert1] varchar(50) NULL,
    [Alert2] varchar(50) NULL,
    [Alert3] varchar(50) NULL,
    [Alert4] varchar(50) NULL,
    [GenericSwitch] varchar(50) NULL,
    [GenericPercent] int NULL,
    [ContainerQuantity] decimal(18,4) NULL,
    [ContainerAwpPrice] decimal(18,2) NULL,
    [ContainerAcqPriceDeprecated] decimal(18,2) NULL,
    [ContainerContractPrice] decimal(18,2) NULL,
    [UnitAwpPrice] decimal(18,4) NULL,
    [UnitAcqPrice] decimal(18,4) NULL,
    [UnitContractPrice] decimal(18,4) NULL,
    [LastPriceUpdate] date NULL,
    [PreviousPriceUpdate] date NULL,
    [LastDateDispensed] date NULL,
    [PriceFormula] varchar(50) NULL,
    [MetricName] varchar(50) NULL,
    [MetricUnit] decimal(18,5) NULL,
    [AwpPriceUpdateSwitch] varchar(50) NULL,
    [AcqPriceUpdateSwitch] varchar(50) NULL,
    [HotListQty] decimal(18,4) NULL,
    [HotListCost] decimal(18,2) NULL,
    [CompoundForm] varchar(50) NULL,
    [CompoundUnit] int NULL,
    [CompoundAdministration] int NULL,
    [Name] varchar(100) NULL,
    [Hcpcs] varchar(50) NULL,
    [ProcedureModifierCode] varchar(50) NULL,
    [TherapeuticNoHitOption] varchar(50) NULL,
    [MonographNdcNumber] varchar(50) NULL,
    [CompoundUpdateAWP] varchar(50) NULL,
    [CompoundUpdateACQ] varchar(50) NULL,
    [LastModified] datetime NULL,
    [IsValid] bit NULL,
    [GenericLabelText] varchar(50) NULL,
    [DoNotPrintMedGuide] char(1) NULL,
    [QuickLookup] varchar(50) NULL,
    [CustomField1] varchar(50) NULL,
    [CustomField2] varchar(50) NULL,
    [CustomField3] varchar(50) NULL,
    [CustomField4] varchar(50) NULL,
    [DefaultGeneric] bit NOT NULL,
    [ContainerWacPrice] decimal(18,2) NULL,
    [UnitWacPrice] decimal(18,4) NULL,
    [PreferredVendor] varchar(50) NULL,
    [CompoundType] char(2) NULL,
    [CompoundIngredientModifierCodes] varchar(200) NULL,
    [RouteOfAdministration] varchar(100) NULL,
    [Is340B] bit NOT NULL,
    [PotencyUnitCode] varchar(50) NOT NULL,
    [MinimumDispenseQuantity] decimal(10,4) NOT NULL,
    [ExpirationDays] int NULL,
    [Alert5] varchar(50) NULL,
    [OrganizationId] varchar(50) NULL,
    [DoNotSub] bit NULL,
    [RxLoyaltyPriceFormula] varchar(50) NULL,
    [StockLocation] varchar(50) NULL,
    [CategoryId] int NULL,
    [DateCreated] datetime NULL,
    [WillCallLocation] int NOT NULL,
    [SpecialtyDrug] varchar(50) NULL,
    [Vaccine] varchar(50) NULL,
    [SigVerb] varchar(50) NULL,
    [SigRoute] varchar(50) NULL,
    [GPIOverride] varchar(20) NULL,
    [AlternativeProductQualifier] int NULL,
    [AlternativeProductId] varchar(200) NULL,
    [VaccineGroup] varchar(50) NULL,
    [PriceReportQuantity] decimal(19,3) NULL,
    [ExcludeEquivalent] bit NULL,
    [ContainerQuantityPartition] bit NULL,
    [EquivalentOrdering] int NULL,
    [DoNotAutoFill] bit NULL,
    [VisDate] date NULL,
    [VisVersion] varchar(50) NULL,
    [CompoundSpecialityType] int NULL,
    [IncludeDefaultWastage] bit NULL,
    [DefaultWastage] decimal(18,8) NULL,
    [DrugUnitMultiplierId] int NULL,
    [CountryOfOrigin] nvarchar(max) NULL,
    [CentralFillServiceId] int NULL,
    [DoNotCf] bit NULL,
    [OnCfFormulary] bit NULL,
    [UnitOfUseQTY] decimal(8,3) NULL,
    [LabelsPerUnit] int NULL,
    [IsHazardous] bit NOT NULL,
    [CompoundLevelOfEffort] int NULL,
    [ContainerMfpPrice] decimal(10,2) NULL,
    [MfpEffectiveDate] date NULL,
    [MfpEndDate] date NULL,
    [DefaultBinId] int NULL,
    [PreferredGeneric] bit NULL,
    [LastACQPerUnit] decimal(18,4) NULL,
    CONSTRAINT [PK_rxqDrug] PRIMARY KEY ([DrugId])
);

-- Indexes
CREATE INDEX [IX_cDrug] ON [dbo].[rxqDrug] ([NdcNumber]);
CREATE INDEX [IX_cDrug_1] ON [dbo].[rxqDrug] ([Name]);
CREATE INDEX [IX_Drug_PriceFormula] ON [dbo].[rxqDrug] ([PriceFormula]);
CREATE INDEX [IX_rxqDrug_2] ON [dbo].[rxqDrug] ([QuickLookup]);
CREATE INDEX [NonClusteredIndex-OrgId] ON [dbo].[rxqDrug] ([OrganizationId]);
