-- rxqEScriptDoctor   (0 rows, 59 columns)
-- Source: RXQRXCOMPOUNDSTORE (Liberty). Read-only reference DDL, synthesized from catalog metadata.
CREATE TABLE [dbo].[rxqEScriptDoctor] (
    [cEScriptDoctorId] int IDENTITY NOT NULL,
    [SurescriptProviderId] char(13) NOT NULL,
    [DEA] varchar(25) NOT NULL,
    [StateLicenseNumber] varchar(25) NULL,
    [ReferenceNumberAlt1] varchar(25) NULL,
    [ReferenceNumberAlt1Qualifier] char(10) NULL,
    [SpecialtyCodePrimary] char(10) NULL,
    [PrefixName] varchar(10) NULL,
    [LastName] varchar(35) NULL,
    [FirstName] varchar(35) NULL,
    [MiddleName] varchar(35) NULL,
    [SuffixName] varchar(10) NULL,
    [ClinicName] varchar(35) NULL,
    [AddressLine1] varchar(35) NULL,
    [AddressLine2] varchar(35) NULL,
    [City] varchar(35) NULL,
    [State] char(10) NULL,
    [Zip] varchar(11) NULL,
    [PhonePrimary] varchar(25) NULL,
    [Fax] varchar(25) NULL,
    [Email] varchar(80) NULL,
    [PhoneAlt1] varchar(25) NULL,
    [PhoneAlt1Qualifier] char(10) NULL,
    [PhoneAlt2] varchar(25) NULL,
    [PhoneAlt2Qualifier] char(10) NULL,
    [PhoneAlt3] varchar(25) NULL,
    [PhoneAlt3Qualifier] char(10) NULL,
    [PhoneAlt4] varchar(25) NULL,
    [PhoneAlt4Qualifier] char(10) NULL,
    [PhoneAlt5] varchar(25) NULL,
    [PhoneAlt5Qualifier] char(10) NULL,
    [ActiveStartTime] datetime NULL,
    [ActiveEndTime] datetime NULL,
    [ServiceLevel] char(10) NULL,
    [PartnerAccount] varchar(25) NULL,
    [LastModifiedDate] datetime NULL,
    [RecordChange] char(10) NULL,
    [OldServiceLevel] char(10) NULL,
    [TextServiceLevel] varchar(100) NULL,
    [TextServiceLevelChange] varchar(100) NULL,
    [Version] char(10) NULL,
    [NPI] varchar(10) NULL,
    [NPILocation] varchar(13) NULL,
    [LastModified] datetime NULL,
    [IsValid] bit NULL,
    [SpecialtyType1] varchar(35) NULL,
    [SpecialtyType2] varchar(35) NULL,
    [SpecialtyType3] varchar(35) NULL,
    [SpecialtyType4] varchar(35) NULL,
    [FileId] varchar(35) NULL,
    [MedicareNumber] varchar(35) NULL,
    [MedicaidNumber] varchar(35) NULL,
    [DentistLicenseNumber] varchar(35) NULL,
    [UPIN] varchar(35) NULL,
    [PPONumber] varchar(35) NULL,
    [SocialSecurity] varchar(35) NULL,
    [PriorAuthorization] varchar(35) NULL,
    [MutuallyDefined] varchar(35) NULL,
    [InStoreNCPDPID] varchar(7) NULL,
    CONSTRAINT [PK_rxqEScriptDoctor] PRIMARY KEY ([SurescriptProviderId])
);

-- Indexes
CREATE INDEX [IX_rxqEScriptDoctorDEA] ON [dbo].[rxqEScriptDoctor] ([DEA]);
CREATE INDEX [IX_rxqEScriptDoctorName] ON [dbo].[rxqEScriptDoctor] ([LastName]);
CREATE INDEX [IX_rxqEScriptDoctorNPI] ON [dbo].[rxqEScriptDoctor] ([NPI]);
