-- rxqInventoryTransferHeader   (0 rows, 34 columns)
-- Source: RXQRXCOMPOUNDSTORE (Liberty). Read-only reference DDL, synthesized from catalog metadata.
CREATE TABLE [dbo].[rxqInventoryTransferHeader] (
    [cInventoryTransferHeaderId] varchar(50) NOT NULL,
    [OriginalDate] datetime NULL,
    [LastModified] datetime NULL,
    [TransferDate] datetime NULL,
    [Comments] nvarchar(500) NULL,
    [Type] int NULL,
    [ToPharmacy] nvarchar(100) NULL,
    [ToAddress1] nvarchar(100) NULL,
    [ToAddress2] nvarchar(100) NULL,
    [ToPostalCode] nvarchar(15) NULL,
    [ToState] nvarchar(2) NULL,
    [ToCity] nvarchar(100) NULL,
    [ToPhone] nvarchar(50) NULL,
    [FromPharmacy] nvarchar(100) NULL,
    [FromAddress1] nvarchar(100) NULL,
    [FromAddress2] nvarchar(100) NULL,
    [FromPostalCode] nvarchar(100) NULL,
    [FromState] nvarchar(15) NULL,
    [FromCity] nvarchar(100) NULL,
    [FromPhone] nvarchar(50) NULL,
    [Status] int NULL,
    [FromPharmacyId] nvarchar(50) NULL,
    [ToPharmacyId] nvarchar(50) NULL,
    [StoreNumber] nvarchar(50) NOT NULL,
    [ToDeaNumber] nvarchar(100) NULL,
    [FromDeaNumber] nvarchar(100) NULL,
    [FromNCPDP] nvarchar(100) NULL,
    [ToNCPDP] nvarchar(100) NULL,
    [ToFax] nvarchar(100) NULL,
    [FromFax] nvarchar(100) NULL,
    [ToDPS] nvarchar(50) NULL,
    [ToNPI] nvarchar(50) NULL,
    [FromDPS] nvarchar(50) NULL,
    [FromNPI] nvarchar(50) NULL,
    CONSTRAINT [PK_rxqInventoryTransferHeader] PRIMARY KEY ([cInventoryTransferHeaderId], [StoreNumber])
);
