-- rxqMTMAlert   (0 rows, 47 columns)
-- Source: RXQRXCOMPOUNDSTORE (Liberty). Read-only reference DDL, synthesized from catalog metadata.
CREATE TABLE [dbo].[rxqMTMAlert] (
    [id] nvarchar(50) NOT NULL,
    [DateCreated] datetime NULL,
    [AlertType] int NULL,
    [ExternalPatientId] nvarchar(max) NULL,
    [PatientFirstName] nvarchar(50) NULL,
    [PatientMiddleName] nvarchar(50) NULL,
    [PatientLastName] nvarchar(50) NULL,
    [PatientDOB] nvarchar(max) NULL,
    [PatientGender] nvarchar(max) NULL,
    [PatientAddress] nvarchar(max) NULL,
    [PatientCity] nvarchar(max) NULL,
    [PatientState] nvarchar(max) NULL,
    [PatientZip] nvarchar(max) NULL,
    [PatientEmail] nvarchar(max) NULL,
    [PatientPhone] nvarchar(max) NULL,
    [MirixaCaseStatus] nvarchar(max) NULL,
    [MirixaProgramName] nvarchar(max) NULL,
    [MirixaProgramMoniker] nvarchar(max) NULL,
    [MirixaCaseSummary] nvarchar(max) NULL,
    [MirixaCaseId] nvarchar(max) NULL,
    [MirixaAppointmentDate] datetime NULL,
    [MirixaCompletedDate] datetime NULL,
    [MirixaBillingCode] nvarchar(max) NULL,
    [MirixaBillingCodeDescription] nvarchar(max) NULL,
    [MirixaPatientDeclineDate] datetime NULL,
    [MirixaDeclineCode] nvarchar(max) NULL,
    [OutcomesIsPrimaryPatient] bit NULL,
    [OutcomesPolicyId] nvarchar(max) NULL,
    [OutcomesClientId] nvarchar(max) NULL,
    [OutcomesPolicyName] nvarchar(max) NULL,
    [OutcomesPlanType] nvarchar(max) NULL,
    [OutcomesCMSContractNumber] nvarchar(max) NULL,
    [OutcomesNeedsCMR] bit NULL,
    [OutcomesTIPsCount] int NULL,
    [OutcomesNeedsAdherenceCheck] bit NULL,
    [OutcomesUnfinishedClaimsCount] int NULL,
    [OutcomesReviewClaimsCount] int NULL,
    [OutcomesPatientPriority] int NULL,
    [DetailsLink] nvarchar(max) NULL,
    [StoreNumber] varchar(50) NOT NULL,
    [AlertRead] bit NULL,
    [PatientId] varchar(50) NULL,
    [StartDate] date NULL,
    [EndDate] date NULL,
    [CompletedDate] date NULL,
    [Object] varchar(max) NULL,
    [Source] varchar(50) NULL,
    CONSTRAINT [PK_rxqMTMAlert] PRIMARY KEY ([id])
);

-- Indexes
CREATE INDEX [nameIndex] ON [dbo].[rxqMTMAlert] ([PatientFirstName], [PatientLastName]);
CREATE INDEX [storeNumberIndex] ON [dbo].[rxqMTMAlert] ([StoreNumber]);
