-- rxqNHPat   (2 rows, 69 columns)
-- Source: RXQRXCOMPOUNDSTORE (Liberty). Read-only reference DDL, synthesized from catalog metadata.
CREATE TABLE [dbo].[rxqNHPat] (
    [cNHPatId] int IDENTITY NOT NULL,
    [RawData] varchar(50) NULL,
    [ErrCode] varchar(50) NULL,
    [NH] varchar(50) NOT NULL,
    [PatientLastName] varchar(50) NOT NULL,
    [PatientFirstName] varchar(50) NOT NULL,
    [PatientMiddleI] varchar(50) NOT NULL,
    [PatientId] varchar(50) NOT NULL,
    [StationNumber] varchar(50) NULL,
    [RoomNumber] varchar(50) NULL,
    [BedNumber] varchar(50) NULL,
    [AdmitMM] varchar(50) NULL,
    [AdmitDD] varchar(50) NULL,
    [AdmitYY] varchar(50) NULL,
    [ReleaseMM] varchar(50) NULL,
    [ReleaseDD] varchar(50) NULL,
    [ReleaseYY] varchar(50) NULL,
    [Deceased] varchar(50) NULL,
    [PriDocPre] varchar(50) NULL,
    [PriDocSuf] int NULL,
    [SecDocPre] varchar(50) NULL,
    [SecDocSuf] int NULL,
    [StandingOrders1] varchar(50) NULL,
    [StandingOrders2] varchar(50) NULL,
    [StandingOrders3] varchar(50) NULL,
    [StandingOrders4] varchar(50) NULL,
    [StandingOrders5] varchar(50) NULL,
    [StandingOrders6] varchar(50) NULL,
    [StandingOrders7] varchar(50) NULL,
    [StandingOrders8] varchar(50) NULL,
    [StandingOrders9] varchar(50) NULL,
    [StandingOrders10] varchar(50) NULL,
    [StandingOrders11] varchar(50) NULL,
    [StandingOrders12] varchar(50) NULL,
    [StandingOrders13] varchar(50) NULL,
    [StandingOrders14] varchar(50) NULL,
    [StandingOrders15] varchar(50) NULL,
    [StandingOrders16] varchar(50) NULL,
    [StandingOrders17] varchar(50) NULL,
    [StandingOrders18] varchar(50) NULL,
    [StandingOrders19] varchar(50) NULL,
    [StandingOrders20] varchar(50) NULL,
    [StandingOrders21] varchar(50) NULL,
    [StandingOrders22] varchar(50) NULL,
    [StandingOrders23] varchar(50) NULL,
    [StandingOrders24] varchar(50) NULL,
    [StandingOrders25] varchar(50) NULL,
    [StandingOrders26] varchar(50) NULL,
    [StandingOrders27] varchar(50) NULL,
    [StandingOrders28] varchar(50) NULL,
    [StandingOrders29] varchar(50) NULL,
    [StandingOrders30] varchar(50) NULL,
    [StandingOrders31] varchar(50) NULL,
    [StandingOrders32] varchar(50) NULL,
    [Comment1] varchar(200) NULL,
    [Comment2] varchar(200) NULL,
    [Comment3] varchar(200) NULL,
    [AdmissionNumber] varchar(50) NULL,
    [LastModified] datetime NULL,
    [IsValid] bit NULL,
    [ExcludeOrdersFromMedSheet] varchar(50) NULL,
    [AdmitStatus] int NULL,
    [DischargeType] int NULL,
    [LeaveOfAbsence] date NULL,
    [LeaveOfAbsenceReason] int NULL,
    [ExpectedReturn] date NULL,
    [Inactive] bit NULL,
    [InactiveStatus] int NULL,
    [LtcVendor] int NULL,
    CONSTRAINT [PK_rxqNHPat] PRIMARY KEY ([NH], [PatientLastName], [PatientFirstName], [PatientMiddleI], [PatientId])
);
