-- rxqOnlineHistory   (0 rows, 202 columns)
-- Source: RXQRXCOMPOUNDSTORE (Liberty). Read-only reference DDL, synthesized from catalog metadata.
CREATE TABLE [dbo].[rxqOnlineHistory] (
    [cOnlineHistoryId] int IDENTITY NOT NULL,
    [ScriptNumber] int NULL,
    [RefillNumber] int NULL,
    [SubmitDate] datetime NULL,
    [PrimaryOrSecondary] varchar(50) NULL,
    [AgencyCode] varchar(50) NULL,
    [BIN] varchar(50) NULL,
    [NCPDPVersion] varchar(50) NULL,
    [TransactionCode] varchar(50) NULL,
    [PCN] varchar(50) NULL,
    [DrugKey] varchar(50) NULL,
    [IngredientCost] varchar(50) NULL,
    [ProfServiceFee] varchar(50) NULL,
    [DispensingFee] varchar(50) NULL,
    [PatientPaidAmt] varchar(50) NULL,
    [OtherAmountQual9] varchar(50) NULL,
    [OtherAmountQual8] varchar(50) NULL,
    [OtherAmountQual7] varchar(50) NULL,
    [OtherAmountQual6] varchar(50) NULL,
    [OtherAmountQual5] varchar(50) NULL,
    [OtherAmountQual4] varchar(50) NULL,
    [OtherAmountQual3] varchar(50) NULL,
    [OtherAmountQual2] varchar(50) NULL,
    [OtherAmountQual1] varchar(50) NULL,
    [OtherAmount9] float NULL,
    [OtherAmount8] float NULL,
    [OtherAmount7] float NULL,
    [OtherAmount6] float NULL,
    [OtherAmount5] float NULL,
    [OtherAmount4] float NULL,
    [OtherAmount3] float NULL,
    [OtherAmount2] float NULL,
    [OtherAmount1] float NULL,
    [FlatTaxAmount] varchar(50) NULL,
    [PercentageTaxAmount] varchar(50) NULL,
    [IncentiveAmount] varchar(50) NULL,
    [UsualCustomaryAmount] varchar(50) NULL,
    [GrossDueAmount] varchar(50) NULL,
    [BasisOfCost] varchar(50) NULL,
    [HeaderStatus] varchar(50) NULL,
    [HeaderMessage] varchar(200) NULL,
    [TransactionResponse] varchar(50) NULL,
    [AuthorizationNumber] varchar(50) NULL,
    [RejectCount] varchar(50) NULL,
    [RejectCode99] varchar(50) NULL,
    [RejectCode98] varchar(50) NULL,
    [RejectCode97] varchar(50) NULL,
    [RejectCode96] varchar(50) NULL,
    [RejectCode95] varchar(50) NULL,
    [RejectCode94] varchar(50) NULL,
    [RejectCode93] varchar(50) NULL,
    [RejectCode92] varchar(50) NULL,
    [RejectCode91] varchar(50) NULL,
    [RejectCode90] varchar(50) NULL,
    [RejectCode89] varchar(50) NULL,
    [RejectCode88] varchar(50) NULL,
    [RejectCode87] varchar(50) NULL,
    [RejectCode86] varchar(50) NULL,
    [RejectCode85] varchar(50) NULL,
    [RejectCode84] varchar(50) NULL,
    [RejectCode83] varchar(50) NULL,
    [RejectCode82] varchar(50) NULL,
    [RejectCode81] varchar(50) NULL,
    [RejectCode80] varchar(50) NULL,
    [RejectCode79] varchar(50) NULL,
    [RejectCode78] varchar(50) NULL,
    [RejectCode77] varchar(50) NULL,
    [RejectCode76] varchar(50) NULL,
    [RejectCode75] varchar(50) NULL,
    [RejectCode74] varchar(50) NULL,
    [RejectCode73] varchar(50) NULL,
    [RejectCode72] varchar(50) NULL,
    [RejectCode71] varchar(50) NULL,
    [RejectCode70] varchar(50) NULL,
    [RejectCode69] varchar(50) NULL,
    [RejectCode68] varchar(50) NULL,
    [RejectCode67] varchar(50) NULL,
    [RejectCode66] varchar(50) NULL,
    [RejectCode65] varchar(50) NULL,
    [RejectCode64] varchar(50) NULL,
    [RejectCode63] varchar(50) NULL,
    [RejectCode62] varchar(50) NULL,
    [RejectCode61] varchar(50) NULL,
    [RejectCode60] varchar(50) NULL,
    [RejectCode59] varchar(50) NULL,
    [RejectCode58] varchar(50) NULL,
    [RejectCode57] varchar(50) NULL,
    [RejectCode56] varchar(50) NULL,
    [RejectCode55] varchar(50) NULL,
    [RejectCode54] varchar(50) NULL,
    [RejectCode53] varchar(50) NULL,
    [RejectCode52] varchar(50) NULL,
    [RejectCode51] varchar(50) NULL,
    [RejectCode50] varchar(50) NULL,
    [RejectCode49] varchar(50) NULL,
    [RejectCode48] varchar(50) NULL,
    [RejectCode47] varchar(50) NULL,
    [RejectCode46] varchar(50) NULL,
    [RejectCode45] varchar(50) NULL,
    [RejectCode44] varchar(50) NULL,
    [RejectCode43] varchar(50) NULL,
    [RejectCode42] varchar(50) NULL,
    [RejectCode41] varchar(50) NULL,
    [RejectCode40] varchar(50) NULL,
    [RejectCode39] varchar(50) NULL,
    [RejectCode38] varchar(50) NULL,
    [RejectCode37] varchar(50) NULL,
    [RejectCode36] varchar(50) NULL,
    [RejectCode35] varchar(50) NULL,
    [RejectCode34] varchar(50) NULL,
    [RejectCode33] varchar(50) NULL,
    [RejectCode32] varchar(50) NULL,
    [RejectCode31] varchar(50) NULL,
    [RejectCode30] varchar(50) NULL,
    [RejectCode29] varchar(50) NULL,
    [RejectCode28] varchar(50) NULL,
    [RejectCode27] varchar(50) NULL,
    [RejectCode26] varchar(50) NULL,
    [RejectCode25] varchar(50) NULL,
    [RejectCode24] varchar(50) NULL,
    [RejectCode23] varchar(50) NULL,
    [RejectCode22] varchar(50) NULL,
    [RejectCode21] varchar(50) NULL,
    [RejectCode20] varchar(50) NULL,
    [RejectCode19] varchar(50) NULL,
    [RejectCode18] varchar(50) NULL,
    [RejectCode17] varchar(50) NULL,
    [RejectCode16] varchar(50) NULL,
    [RejectCode15] varchar(50) NULL,
    [RejectCode14] varchar(50) NULL,
    [RejectCode13] varchar(50) NULL,
    [RejectCode12] varchar(50) NULL,
    [RejectCode11] varchar(50) NULL,
    [RejectCode10] varchar(50) NULL,
    [RejectCode9] varchar(50) NULL,
    [RejectCode8] varchar(50) NULL,
    [RejectCode7] varchar(50) NULL,
    [RejectCode6] varchar(50) NULL,
    [RejectCode5] varchar(50) NULL,
    [RejectCode4] varchar(50) NULL,
    [RejectCode3] varchar(50) NULL,
    [RejectCode2] varchar(50) NULL,
    [RejectCode1] varchar(50) NULL,
    [TransactionMessage] varchar(200) NULL,
    [HelpDeskQualifier] varchar(50) NULL,
    [HelpDeskPhone] varchar(50) NULL,
    [PatientPayAmt] varchar(50) NULL,
    [IngredientCostPaid] varchar(50) NULL,
    [DispensingFeePaid] varchar(50) NULL,
    [TaxExemptIndicator] varchar(50) NULL,
    [FlatTaxPaid] varchar(50) NULL,
    [PercentageTaxPaid] varchar(50) NULL,
    [PercentageTaxRate] varchar(50) NULL,
    [PercentageTaxBasis] varchar(50) NULL,
    [IncentivePaid] varchar(50) NULL,
    [ProfServicePaid] varchar(50) NULL,
    [OtherAmtQual9] varchar(50) NULL,
    [OtherAmtQual8] varchar(50) NULL,
    [OtherAmtQual7] varchar(50) NULL,
    [OtherAmtQual6] varchar(50) NULL,
    [OtherAmtQual5] varchar(50) NULL,
    [OtherAmtQual4] varchar(50) NULL,
    [OtherAmtQual3] varchar(50) NULL,
    [OtherAmtQual2] varchar(50) NULL,
    [OtherAmtQual1] varchar(50) NULL,
    [OtherAmtPaid9] float NULL,
    [OtherAmtPaid8] float NULL,
    [OtherAmtPaid7] float NULL,
    [OtherAmtPaid6] float NULL,
    [OtherAmtPaid5] float NULL,
    [OtherAmtPaid4] float NULL,
    [OtherAmtPaid3] float NULL,
    [OtherAmtPaid2] float NULL,
    [OtherAmtPaid1] float NULL,
    [OtherPayorAmtPaid] varchar(50) NULL,
    [TotalAmountPaid] varchar(50) NULL,
    [BasisOfReimbursement] varchar(50) NULL,
    [AmountTowardsSalesTax] varchar(50) NULL,
    [AccumulatedDeductable] varchar(50) NULL,
    [RemainingDeductable] varchar(50) NULL,
    [RemainingBenefitAmount] varchar(50) NULL,
    [AppliedToPeriodicDeduct] varchar(50) NULL,
    [AmountCopay] varchar(50) NULL,
    [AmountAttribProdSelection] varchar(50) NULL,
    [AmountExceedPeriodicMax] varchar(50) NULL,
    [BasisOfDispensingFee] varchar(50) NULL,
    [BasisOfCopay] varchar(50) NULL,
    [BasisOfFlatTax] varchar(50) NULL,
    [BasisOfPercentageTax] varchar(50) NULL,
    [LastModified] datetime NULL,
    [IsValid] bit NULL,
    [NcpdpId] int NULL,
    [AgencySequence] int NOT NULL,
    [LoggedUser] varchar(max) NULL,
    [RequestedACQ] decimal(9,2) NULL,
    [CurrentDirFee] float NULL,
    [PostDirFee] float NULL,
    [PatientThirdPartyId] int NULL,
    [PaidAtMFP] int NULL,
    [MFPRefundSource] varchar(50) NULL,
    [EstimatedMFPRefund] decimal(10,2) NULL,
    [AACUnderpaid] bit NULL,
    CONSTRAINT [PK_rxqOnlineHistory] PRIMARY KEY ([cOnlineHistoryId])
);

-- Indexes
CREATE INDEX [_dta_index_rxqOnlineHistory_195_626101271__K6_K2_K3_K4_149_150_177_193_197_198] ON [dbo].[rxqOnlineHistory] ([PrimaryOrSecondary], [ScriptNumber], [RefillNumber], [SubmitDate]) INCLUDE ([IngredientCostPaid], [DispensingFeePaid], [TotalAmountPaid], [NcpdpId], [CurrentDirFee], [PostDirFee]);
CREATE INDEX [IDX_OnlineHistory_PriSec_Includes] ON [dbo].[rxqOnlineHistory] ([PrimaryOrSecondary]) INCLUDE ([cOnlineHistoryId], [ScriptNumber], [RefillNumber], [SubmitDate], [BIN], [PCN], [OtherAmountQual9], [OtherAmountQual8], [OtherAmountQual7], [OtherAmountQual6], [OtherAmountQual5], [OtherAmountQual4], [OtherAmountQual3], [OtherAmountQual2], [OtherAmountQual1], [OtherAmount9], [OtherAmount8], [OtherAmount7], [OtherAmount6], [OtherAmount5], [OtherAmount4], [OtherAmount3], [OtherAmount2], [OtherAmount1], [RejectCode10], [RejectCode9], [RejectCode8], [RejectCode7], [RejectCode6], [RejectCode5], [RejectCode4], [RejectCode3], [RejectCode2], [RejectCode1], [IncentivePaid], [NcpdpId]);
CREATE INDEX [IDX_OnlineHistory_PriSec_ScriptFillDateNcp] ON [dbo].[rxqOnlineHistory] ([PrimaryOrSecondary]) INCLUDE ([ScriptNumber], [RefillNumber], [SubmitDate], [NcpdpId]);
CREATE INDEX [IX_cDateTime] ON [dbo].[rxqOnlineHistory] ([SubmitDate]);
CREATE INDEX [IX_OnlineHistory_AgencyCode] ON [dbo].[rxqOnlineHistory] ([AgencyCode]);
CREATE INDEX [IX_OnlineHistory_DrugKey] ON [dbo].[rxqOnlineHistory] ([DrugKey]);
CREATE INDEX [IX_OnlineHistory_PriSecTaxes] ON [dbo].[rxqOnlineHistory] ([PrimaryOrSecondary]) INCLUDE ([ScriptNumber], [RefillNumber], [SubmitDate], [IngredientCostPaid], [DispensingFeePaid], [FlatTaxPaid], [PercentageTaxPaid], [OtherPayorAmtPaid], [TotalAmountPaid]);
CREATE INDEX [IX_OnlineHistory_ScriptNumber_RefillNumber_SubmitDate] ON [dbo].[rxqOnlineHistory] ([ScriptNumber], [RefillNumber], [SubmitDate]) INCLUDE ([TransactionCode], [TransactionResponse]);
CREATE INDEX [IX_rxqOnlineHist_PriSec_OtherPayor] ON [dbo].[rxqOnlineHistory] ([PrimaryOrSecondary]) INCLUDE ([ScriptNumber], [RefillNumber], [SubmitDate], [OtherPayorAmtPaid]);
CREATE INDEX [IXOnlineHist20240124_PriSecIncDirFees1] ON [dbo].[rxqOnlineHistory] ([PrimaryOrSecondary]) INCLUDE ([ScriptNumber], [RefillNumber], [SubmitDate], [IngredientCostPaid], [DispensingFeePaid], [TotalAmountPaid], [NcpdpId], [CurrentDirFee], [PostDirFee]);
CREATE INDEX [IXOnlineHist20240124_PriSecIncDirFees2] ON [dbo].[rxqOnlineHistory] ([PrimaryOrSecondary]) INCLUDE ([ScriptNumber], [RefillNumber], [SubmitDate], [BIN], [PCN], [OtherAmountQual9], [OtherAmountQual8], [OtherAmountQual7], [OtherAmountQual6], [OtherAmountQual5], [OtherAmountQual4], [OtherAmountQual3], [OtherAmountQual2], [OtherAmountQual1], [OtherAmount9], [OtherAmount8], [OtherAmount7], [OtherAmount6], [OtherAmount5], [OtherAmount4], [OtherAmount3], [OtherAmount2], [OtherAmount1], [RejectCode10], [RejectCode9], [RejectCode8], [RejectCode7], [RejectCode6], [RejectCode5], [RejectCode4], [RejectCode3], [RejectCode2], [RejectCode1], [IngredientCostPaid], [DispensingFeePaid], [IncentivePaid], [TotalAmountPaid], [NcpdpId], [CurrentDirFee], [PostDirFee]);
CREATE INDEX [LibertyAuto_9_8_rxqOnlineHistory] ON [dbo].[rxqOnlineHistory] ([PrimaryOrSecondary]) INCLUDE ([cOnlineHistoryId], [ScriptNumber], [RefillNumber], [SubmitDate], [AgencyCode], [BIN], [PCN]);
CREATE INDEX [LibertyAuto_96_95_rxqOnlineHistory] ON [dbo].[rxqOnlineHistory] ([AgencySequence]);
