-- rxqPatientAccountReceivableHistory   (0 rows, 29 columns)
-- Source: RXQRXCOMPOUNDSTORE (Liberty). Read-only reference DDL, synthesized from catalog metadata.
CREATE TABLE [dbo].[rxqPatientAccountReceivableHistory] (
    [cPatientAccountReceivableHistoryId] int IDENTITY NOT NULL,
    [AgingDate] datetime NOT NULL,
    [AccountId] varchar(50) NOT NULL,
    [Lastname] varchar(50) NULL,
    [FirstName] varchar(50) NULL,
    [MiddleInitial] varchar(50) NULL,
    [AccountNumber] varchar(50) NULL,
    [CreditLimit] varchar(50) NULL,
    [FinanceChargeSwitch] varchar(50) NULL,
    [FinanceChargePeriod] varchar(50) NULL,
    [PrintCode] varchar(50) NULL,
    [LastPaymentAmount] varchar(50) NULL,
    [LastPaymentDate] date NULL,
    [ResponsibleIdentifier] varchar(50) NULL,
    [YearToDateInterest] varchar(50) NULL,
    [PreviousBalance] varchar(50) NULL,
    [AmountDue] varchar(50) NULL,
    [Over30Days] varchar(50) NULL,
    [Over60Days] varchar(50) NULL,
    [Over90Days] varchar(50) NULL,
    [Over120Days] varchar(50) NULL,
    [CurrentDebits] varchar(50) NULL,
    [CurrentCredits] varchar(50) NULL,
    [TotalBalance] varchar(50) NULL,
    [YearToDateMedical] varchar(50) NULL,
    [FinanceChargeFlag] varchar(50) NULL,
    [LastModified] datetime NULL,
    [IsValid] bit NULL,
    [cAccountReceivablePrintCodeId] int NULL,
    CONSTRAINT [PK_rxqPatientAccountReceivableHistory] PRIMARY KEY ([AgingDate], [AccountId])
);
