-- rxqParameterStore   (1 rows, 72 columns)
-- Source: RXQRXCOMPOUNDSTORE (Liberty). Read-only reference DDL, synthesized from catalog metadata.
CREATE TABLE [dbo].[rxqParameterStore] (
    [cParameterStoreId] int IDENTITY NOT NULL,
    [LabelAddress] varchar(50) NULL,
    [PointOfSale] varchar(50) NULL,
    [AlternateCityDisplay] varchar(50) NULL,
    [WorkInvoiceNumber] int NULL,
    [PharmacyName] varchar(50) NULL,
    [PharmacyStreet] varchar(50) NULL,
    [PharmacyCity] varchar(50) NULL,
    [PharmacyState] varchar(50) NULL,
    [PharmacyZipA] varchar(50) NULL,
    [PharmacyZipB] varchar(50) NULL,
    [PharmacyPhone] varchar(50) NULL,
    [FederalIdNumber] varchar(50) NULL,
    [ContainerChargeA] decimal(9,2) NULL,
    [ContainerChargeB] decimal(9,2) NULL,
    [SalesTaxMedical] decimal(9,4) NULL,
    [SalesTaxNonMedical] decimal(9,4) NULL,
    [DaysSuppliedRequired] varchar(50) NULL,
    [FormulaPriority] varchar(50) NULL,
    [FinanceCharge] decimal(9,3) NULL,
    [AR_DefaultCode] varchar(50) NULL,
    [AR_FinanceChargeCode] int NULL,
    [AR_CreditLimit] int NULL,
    [PrintRph] varchar(50) NULL,
    [PrintRefilsRemaining] varchar(50) NULL,
    [PrintExpirationDate] varchar(50) NULL,
    [PrintLabel] varchar(50) NULL,
    [ExtendDailyLog] varchar(50) NULL,
    [RoundUpToAmount] varchar(50) NULL,
    [PercentGenericSp] int NULL,
    [PharmacyNabp] int NULL,
    [LabelHeadingsSwitch] varchar(50) NULL,
    [DFlag] varchar(50) NULL,
    [PharmacyFax] varchar(50) NULL,
    [PrivatePhoneNumber] varchar(50) NULL,
    [EmailAddress] varchar(50) NULL,
    [DeaNumber] varchar(50) NULL,
    [DpsNumber] varchar(50) NULL,
    [NationalProviderId] varchar(50) NULL,
    [ePrescribingCode] varchar(50) NULL,
    [ePrescribingPassword] varchar(50) NULL,
    [StoreNumber] varchar(50) NULL,
    [LastModified] datetime NULL,
    [IsValid] bit NULL,
    [EnableTextMessaging] char(1) NULL,
    [ShowReleaseNotesAfter] varchar(50) NULL,
    [DefaultServiceFee] decimal(9,2) NULL,
    [NcpdpPharmacyServiceType] char(2) NULL,
    [LastRXQVersion] varchar(50) NULL,
    [BZQDatabase] varchar(max) NULL,
    [BZQServer] varchar(max) NULL,
    [SerialNumber] varchar(50) NULL,
    [FlatTaxAmount] decimal(9,2) NOT NULL,
    [EnableVoiceMessaging] bit NULL,
    [EnableStoreCustomWrkFlw] bit NULL,
    [LastAutoBinAssigned] varchar(50) NULL,
    [LastAutoBinAssignedDate] datetime NULL,
    [AutoBinCycleDays] int NULL,
    [UseAutoBinAssign] bit NULL,
    [NotificationEmail] varchar(50) NULL,
    [RxqSerialNumber] varchar(200) NULL,
    [ImmunizationFee] decimal(9,2) NULL,
    [PharmacyHours] varchar(max) NULL,
    [BillImmunizationCash] int NULL,
    [ChargeSalesTaxCashRx] bit NULL,
    [cAccountReceivablePrintCodeId] int NULL,
    [PharmacySuite] varchar(50) NULL,
    [Latitude] decimal(12,9) NULL,
    [Longitude] decimal(12,9) NULL,
    [Timezone_StandardName] varchar(50) NULL,
    [Timezone_DisplayName] varchar(50) NULL,
    [Timezone_BaseUtcOffset] varchar(50) NULL,
    CONSTRAINT [PK_rxqParameterStore] PRIMARY KEY ([cParameterStoreId])
);

-- Indexes
CREATE UNIQUE INDEX [IX_rxqParameterStore_StoreNumber] ON [dbo].[rxqParameterStore] ([StoreNumber]);
