-- rxqPatient   (165,756 rows, 117 columns)
-- Source: RXQRXCOMPOUNDSTORE (Liberty). Read-only reference DDL, synthesized from catalog metadata.
-- NOTE: mirrored into liberty_link_stage by the eMed ETL.
CREATE TABLE [dbo].[rxqPatient] (
    [LastName] varchar(50) NULL,
    [FirstName] varchar(50) NULL,
    [MiddleInitial] varchar(50) NULL,
    [PatientId] varchar(50) NOT NULL,
    [Street] varchar(50) NULL,
    [City] varchar(50) NULL,
    [State] varchar(50) NULL,
    [Zip] varchar(50) NULL,
    [ZipPlus] varchar(50) NULL,
    [Phone] varchar(50) NULL,
    [DateOfBirth] date NULL,
    [Gender] varchar(50) NULL,
    [SocialSecurityNumber] varchar(50) NULL,
    [PriceFormula] varchar(50) NULL,
    [Discount] float NULL,
    [ChildProofTop] varchar(50) NULL,
    [Language] varchar(50) NULL,
    [ProfileFrequency] varchar(50) NULL,
    [RxCountYearToDate] int NULL,
    [ChargeCode] varchar(50) NULL,
    [StartDate] date NULL,
    [LastDateUsed] date NULL,
    [NursingHome] varchar(50) NULL,
    [ResponsiblePartySwitch] varchar(50) NULL,
    [Comment] nvarchar(max) NULL,
    [CrossCheckSwitch] varchar(50) NULL,
    [DriversLicenseNumber] varchar(50) NULL,
    [MilitaryId] varchar(50) NULL,
    [SmokerCode] varchar(50) NULL,
    [PregnancyIndicator] varchar(50) NULL,
    [EmailAddress] varchar(50) NULL,
    [HippaSwitch] varchar(50) NULL,
    [HippaDate] date NULL,
    [TaxCode] varchar(50) NULL,
    [TaxExemptNumber] varchar(50) NULL,
    [OverTheCounterDiscount] int NULL,
    [AlternateStreet] varchar(50) NULL,
    [AlternateCity] varchar(50) NULL,
    [AlternateState] varchar(50) NULL,
    [AlternateZip] varchar(50) NULL,
    [AlternateZipPlus] varchar(50) NULL,
    [AlternatePhone] varchar(50) NULL,
    [Suite] varchar(50) NULL,
    [AlternateSuite] varchar(50) NULL,
    [CountryCode] varchar(50) NULL,
    [AlternateCountryCode] varchar(50) NULL,
    [DeliveryDefault] varchar(50) NULL,
    [OTCVolumeDiscount] varchar(50) NULL,
    [LastModified] datetime NULL,
    [IsValid] bit NULL,
    [FacilityChargeAccountId] varchar(50) NULL,
    [TextingOption] char(1) NULL,
    [PhoneType] char(2) NULL,
    [AlternatePhoneType] char(2) NULL,
    [LastDatePOS] date NULL,
    [CustomField1] varchar(50) NULL,
    [CustomField2] varchar(50) NULL,
    [CustomField3] varchar(50) NULL,
    [CustomField4] varchar(50) NULL,
    [UnitDose] bit NULL,
    [GlobalId] varchar(50) NULL,
    [PlaceOfService] varchar(50) NULL,
    [PatientResidence] varchar(50) NULL,
    [FacilityCharge] bit NULL,
    [AddressVerified] date NULL,
    [InActive] bit NULL,
    [SalesForceReferral] varchar(75) NULL,
    [SalesForceReferralId] varchar(50) NULL,
    [cQueueId] int NULL,
    [HouseholdId] varchar(50) NULL,
    [AccountId] varchar(50) NULL,
    [Relation] varchar(1) NULL,
    [OfficeUse] bit NULL,
    [PassportNumber] varchar(50) NULL,
    [AutoFill] bit NULL,
    [RxLoyalty] bit NULL,
    [FacilityChargeOTCOnly] bit NULL,
    [SendRxAlertText] bit NULL,
    [SendRxAlertEmail] bit NULL,
    [SendRxAlertVoice] bit NULL,
    [RxAlertVoiceType] varchar(50) NULL,
    [MedSyncStartDate1] datetime NULL,
    [MedSyncDays1] int NULL,
    [MedSyncStartDate2] datetime NULL,
    [MedSyncDays2] int NULL,
    [PrintMonograph] bit NULL,
    [MedicalConditionsSwitch] bit NULL,
    [DeceasedFlag] bit NULL,
    [DeceasedDate] date NULL,
    [HIC] varchar(50) NULL,
    [Ranking] varchar(50) NULL,
    [Is340B] bit NULL,
    [MedicareBeneficiaryId] varchar(50) NULL,
    [DeliveryAddress] bit NULL,
    [SpeciesCode] int NULL,
    [VaccineRegistryConsent] bit NULL,
    [Breastfeeding] bit NULL,
    [Race] varchar(50) NULL,
    [Ethnicity] varchar(50) NULL,
    [Weight] int NULL,
    [PrimaryAddressId] int NULL,
    [AlternateAddressId] int NULL,
    [BillingAddressId] int NULL,
    [ShippingAddressId] int NULL,
    [DeliveryAddressId] int NULL,
    [PatientPhone1Id] int NULL,
    [PatientPhone2Id] int NULL,
    [RxAlertVoicePhoneId] int NULL,
    [Rx365Id] uniqueidentifier NULL,
    [Rx365LastLogin] datetime NULL,
    [Rx365StoreNumber] varchar(50) NULL,
    [Rx365Email] varchar(500) NULL,
    [SupportedLanguageCode] varchar(3) NULL,
    [PatientConsolidationHistoryId] uniqueidentifier NULL,
    [LastVisitDate] date NULL,
    [LastVisitDateImported] bit NULL,
    [DriversLicenseState] varchar(50) NULL,
    CONSTRAINT [PK_rxqPatient] PRIMARY KEY ([PatientId])
);

-- Indexes
CREATE INDEX [_dta_index_rxqPatient_195_1026102696__K5_K187_K186_K181_K49_K171_2_3_4_12_13_14_47_54_56_57_60_86_87_88_89_141_143_155_168_170_] ON [dbo].[rxqPatient] ([PatientId], [PatientPhone2Id], [PatientPhone1Id], [PrimaryAddressId], [NursingHome], [Ranking]) INCLUDE ([LastName], [FirstName], [MiddleInitial], [DateOfBirth], [Gender], [SocialSecurityNumber], [StartDate], [Comment], [DriversLicenseNumber], [MilitaryId], [EmailAddress], [CustomField1], [CustomField2], [CustomField3], [CustomField4], [GlobalId], [PatientResidence], [AutoFill], [DeceasedFlag], [HIC], [Is340B], [SpeciesCode]);
CREATE INDEX [IDX_Pat_AccId] ON [dbo].[rxqPatient] ([AccountId]);
CREATE INDEX [IDX_Pat_HHID] ON [dbo].[rxqPatient] ([HouseholdId]);
CREATE INDEX [IX_AltPhone] ON [dbo].[rxqPatient] ([AlternatePhone]);
CREATE INDEX [IX_cPatient] ON [dbo].[rxqPatient] ([LastName]);
CREATE INDEX [IX_cPatient_2] ON [dbo].[rxqPatient] ([Phone]);
CREATE INDEX [IX_cPatient_3] ON [dbo].[rxqPatient] ([SocialSecurityNumber]);
CREATE INDEX [IX_Patient_PriceFormula] ON [dbo].[rxqPatient] ([PriceFormula]);
CREATE INDEX [IX_rxqPatient_DateOfBirth] ON [dbo].[rxqPatient] ([DateOfBirth]);
CREATE INDEX [IX_rxqPatient_EmailAddress] ON [dbo].[rxqPatient] ([EmailAddress]);
CREATE INDEX [IX_rxqPatient_GlobalId] ON [dbo].[rxqPatient] ([GlobalId]);
CREATE INDEX [PatientSearch] ON [dbo].[rxqPatient] ([PatientId], [MiddleInitial], [GlobalId], [DriversLicenseNumber], [PassportNumber], [MedicareBeneficiaryId], [HIC], [CustomField1], [CustomField2], [CustomField3], [CustomField4], [FirstName], [LastName], [DateOfBirth], [Phone]);
