-- rxqScriptTransaction   (602,607 rows, 155 columns)
-- Source: RXQRXCOMPOUNDSTORE (Liberty). Read-only reference DDL, synthesized from catalog metadata.
-- NOTE: mirrored into liberty_link_stage by the eMed ETL.
CREATE TABLE [dbo].[rxqScriptTransaction] (
    [cScriptTransactionId] numeric(18,0) IDENTITY NOT NULL,
    [ScriptNumber] int NOT NULL,
    [RefillNumber] int NOT NULL,
    [AdministrativeCharge] decimal(9,2) NULL,
    [Agency] varchar(50) NULL,
    [AuthorizationNumber] varchar(50) NULL,
    [ChargeCode] varchar(50) NULL,
    [Copay] decimal(9,2) NULL,
    [Cost] decimal(9,2) NULL,
    [CostBase] varchar(50) NULL,
    [CountedByUser] varchar(50) NULL,
    [CouponAmount] decimal(9,2) NULL,
    [CouponNumber] varchar(50) NULL,
    [CouponType] varchar(50) NULL,
    [DateDispensedSQL] date NULL,
    [DaysSupply] varchar(50) NULL,
    [DeliveryCharge] decimal(9,2) NULL,
    [DenialClarification] varchar(50) NULL,
    [DiagnosisCode] varchar(50) NULL,
    [Discount] varchar(50) NULL,
    [DispenseAsWritten] varchar(50) NULL,
    [DrugId] varchar(50) NULL,
    [ExpirationDate] date NULL,
    [Fee] decimal(9,2) NULL,
    [Icd9Code] varchar(50) NULL,
    [LevelOfService] varchar(50) NULL,
    [LoggedInUser] varchar(50) NULL,
    [LotNumber] varchar(50) NULL,
    [NCPDCAmountDue] varchar(50) NULL,
    [NCPDCBasisOfCost] varchar(50) NULL,
    [NCPDCCustomerLocation] varchar(50) NULL,
    [NCPDCDenialClarification] varchar(50) NULL,
    [NCPDCDispenseAsWritten] varchar(50) NULL,
    [NCPDCDispensingFee] varchar(50) NULL,
    [NCPDCEligabilityClarification] varchar(50) NULL,
    [NCPDCGrossAmountDue] varchar(50) NULL,
    [NCPDCIngredientCost] varchar(50) NULL,
    [NCPDCLevelOfService] varchar(50) NULL,
    [NCPDCOtherPayorAmount] varchar(50) NULL,
    [NCPDCPatientPaidAmount] varchar(50) NULL,
    [NCPDCPriorAuthorizationCode] varchar(50) NULL,
    [NCPDCPriorAuthorizationNumber] varchar(50) NULL,
    [NCPDCSalesTax] varchar(50) NULL,
    [NCPDCUsualCustomaryCharge] varchar(50) NULL,
    [NursingHome] varchar(50) NULL,
    [OtherCharge] decimal(9,2) NULL,
    [OtherCoverageCode] varchar(50) NULL,
    [PaidSwitch] varchar(50) NULL,
    [PaidDate] date NULL,
    [PcnNumber] varchar(50) NULL,
    [PosScanFlag] varchar(50) NULL,
    [PostageCharge] decimal(9,2) NULL,
    [PriceFormula] varchar(50) NULL,
    [PriceFormulaOriginal] varchar(50) NULL,
    [PrimaryRejectedFlag] varchar(50) NULL,
    [QuantityDispensed] decimal(9,3) NULL,
    [RequestedACQ] decimal(9,2) NULL,
    [RequestedAWP] decimal(9,2) NULL,
    [RequestedCON] decimal(9,2) NULL,
    [RequestedCopay] decimal(9,2) NULL,
    [RequestedDiscount] decimal(9,2) NULL,
    [RequestedFee] decimal(9,2) NULL,
    [RequestedTax] decimal(9,2) NULL,
    [RequestedTotal] decimal(9,2) NULL,
    [RphInitials] varchar(50) NULL,
    [RxpIndicator] varchar(50) NULL,
    [ShippingCharge] decimal(9,2) NULL,
    [Sigs] nvarchar(500) NULL,
    [StoreNumber] varchar(50) NULL,
    [Tax] decimal(9,2) NULL,
    [TimeStampAsOfDate] date NULL,
    [Total] decimal(9,2) NULL,
    [TriplicateSerialNumber] varchar(50) NULL,
    [UnitDoseIndicator] varchar(50) NULL,
    [UsualAndCustomary] decimal(9,2) NULL,
    [UsualAndCustomarySwitch] varchar(50) NULL,
    [WorkersCompFormType] varchar(50) NULL,
    [WorkFlowStatus] varchar(50) NULL,
    [LastModified] datetime NULL,
    [IsValid] bit NULL,
    [NCPDPProcedureModifierCodes] varchar(50) NULL,
    [NCPDPSubmissionClarificationCodes] varchar(50) NULL,
    [NCPDPDelayReasonCode] char(2) NULL,
    [NCPDPRouteOfAdministration] varchar(50) NULL,
    [IncentiveAmount] decimal(9,2) NULL,
    [NCPDPRejectCodes] varchar(200) NULL,
    [NCPDPResponsePricingSegment] varbinary(max) NULL,
    [IntermediaryAuthorizationType] varchar(50) NULL,
    [IntermediaryAuthorization] varchar(50) NULL,
    [PackingListNumber] int NULL,
    [WorkflowLocation] int NULL,
    [DecodedSigs] nvarchar(500) NULL,
    [PosPickupDateTime] datetime NULL,
    [cQueueId] int NULL,
    [PickupPatientId] varchar(50) NULL,
    [PickupDriversLicense] varchar(50) NULL,
    [PickupRelationship] varchar(50) NULL,
    [HcfaResubmitCode] varchar(100) NULL,
    [HcfaOriginalReferenceCode] varchar(100) NULL,
    [HcfaPriorAuthorization] varchar(100) NULL,
    [AccountId] varchar(50) NULL,
    [ManualPriceChangeUser] varchar(50) NULL,
    [EstimatedDirFee] decimal(9,2) NULL,
    [DiagnosisCodeType] varchar(50) NULL,
    [PromiseDateTime] datetime NULL,
    [PickupTimeType] varchar(50) NULL,
    [HasProblem] bit NULL,
    [WorkQueueNote] varchar(1026) NULL,
    [ProblemCategory] varchar(256) NULL,
    [PrintLabelDateTime] datetime NULL,
    [Printed] bit NULL,
    [WorkflowLock] nvarchar(max) NULL,
    [CountImage] varchar(256) NULL,
    [NextDispensedQuantity] decimal(9,3) NULL,
    [TimeStampComputerDateTime] datetime NULL,
    [AgencySequence] int NULL,
    [PartialFill] int NULL,
    [eVoucherAmount] decimal(9,2) NULL,
    [WholesalerRebateAmount] decimal(9,3) NULL,
    [Confirmed] int NULL,
    [Source] varchar(50) NULL,
    [PrescriptionDirectionOverflowPrinted] bit NULL,
    [AdminSite] varchar(5) NULL,
    [TelephoneAuthorizedBy] varchar(200) NULL,
    [TelephoneReceivingRph] varchar(200) NULL,
    [ArPosted] bit NULL,
    [TransactionNumber] int NULL,
    [RequestedIncentiveFee] decimal(9,3) NULL,
    [RequestedAdministrativeFee] decimal(9,3) NULL,
    [PartialPaymentType] int NULL,
    [DaySupplyInsuranceOverride] int NULL,
    [VisDate] date NULL,
    [VisVersion] varchar(50) NULL,
    [NADAC] decimal(12,6) NULL,
    [StoreNumberInventory] varchar(50) NULL,
    [QuestionnaireReviewId] uniqueidentifier NULL,
    [DrugUnitMultiplierId] int NULL,
    [DecodedEnglishSigs] nvarchar(500) NULL,
    [AppointmentBookingId] uniqueidentifier NULL,
    [PrintFirstLabelDateTime] datetime NULL,
    [PrintFirstLabelInitials] varchar(50) NULL,
    [PatientWaiting] bit NULL,
    [PickupPreference] int NULL,
    [CentralFillServiceFee] decimal(9,2) NULL,
    [PatientThirdPartyId] int NULL,
    [DeliveryStatus] int NULL,
    [AverageAcq] decimal(18,4) NULL,
    [AdherenceType] int NULL,
    [BinId] int NULL,
    [LastAssignedBin] int NULL,
    [DrugType] int NULL,
    [AACUnderpaid] bit NULL,
    [AACPrinted] bit NULL,
    [AccountReceivableID] int NULL,
    [RequestedWAC] decimal(15,2) NULL,
    CONSTRAINT [PK_rxqScriptTransaction] PRIMARY KEY ([ScriptNumber], [RefillNumber])
);

-- Indexes
CREATE INDEX [_dta_index_rxqScriptTransaction_36_558625033__K18_K105_K2_K3_K5_K130_K27_K24_4_6_8_9_10_21_25_26_29_30_33_34_48_58_59_62_63_66_] ON [dbo].[rxqScriptTransaction] ([DateDispensedSQL], [WorkflowLocation], [ScriptNumber], [RefillNumber], [Agency], [AgencySequence], [DrugId], [DiagnosisCode]) INCLUDE ([AdministrativeCharge], [AuthorizationNumber], [ChargeCode], [Copay], [Cost], [DaysSupply], [Discount], [DispenseAsWritten], [ExpirationDate], [Fee], [LoggedInUser], [LotNumber], [NCPDCPriorAuthorizationNumber], [PcnNumber], [PosScanFlag], [PriceFormula], [PriceFormulaOriginal], [QuantityDispensed], [RequestedACQ], [RequestedAWP], [RequestedCON], [RequestedTotal], [RphInitials], [RxpIndicator], [StoreNumber], [Tax], [TimeStampAsOfDate], [Total], [TriplicateSerialNumber], [UsualAndCustomary], [WorkFlowStatus], [LastModified], [NCPDPSubmissionClarificationCodes], [IncentiveAmount], [NCPDPRejectCodes], [DecodedSigs], [PosPickupDateTime], [cQueueId], [ManualPriceChangeUser], [TimeStampComputerDateTime], [PartialFill], [eVoucherAmount], [WholesalerRebateAmount], [AdminSite], [PartialPaymentType], [DaySupplyInsuranceOverride], [NADAC]);
CREATE INDEX [_dta_index_rxqScriptTransaction_c_195_558625033__K18] ON [dbo].[rxqScriptTransaction] ([DateDispensedSQL]);
CREATE INDEX [IDX_rxqScriptTransaction_WorkflowStatus_HasProblem] ON [dbo].[rxqScriptTransaction] ([WorkFlowStatus], [HasProblem]) INCLUDE ([ScriptNumber], [RefillNumber], [Agency], [Copay], [CountedByUser], [DateDispensedSQL], [DrugId], [LoggedInUser], [LotNumber], [PosScanFlag], [PriceFormula], [QuantityDispensed], [RphInitials], [RxpIndicator], [Total], [WorkflowLocation], [cQueueId], [PromiseDateTime], [PickupTimeType], [WorkQueueNote], [PrintLabelDateTime], [Printed], [TimeStampComputerDateTime], [PartialFill], [Source]);
CREATE INDEX [IDX_ScriptTransaction_LastModified_ScriptFill] ON [dbo].[rxqScriptTransaction] ([LastModified]) INCLUDE ([ScriptNumber], [RefillNumber]);
CREATE INDEX [IDX_ScriptTransaction_QtyStatus_PrintedScriptFill] ON [dbo].[rxqScriptTransaction] ([QuantityDispensed], [WorkFlowStatus]) INCLUDE ([ScriptNumber], [RefillNumber], [DateDispensedSQL], [Printed], [TimeStampComputerDateTime]);
CREATE INDEX [IDX_ScriptTransaction_QtyStatusProblem_ScriptFillDates] ON [dbo].[rxqScriptTransaction] ([QuantityDispensed], [WorkFlowStatus], [HasProblem]) INCLUDE ([ScriptNumber], [RefillNumber], [DateDispensedSQL], [TimeStampComputerDateTime]);
CREATE INDEX [IX_cScriptTransaction] ON [dbo].[rxqScriptTransaction] ([ScriptNumber]);
CREATE INDEX [IX_DrugDataView] ON [dbo].[rxqScriptTransaction] ([ScriptNumber], [RefillNumber], [DateDispensedSQL], [DrugId]);
CREATE INDEX [IX_rxqScriptTrans_DateDispSQL_incls] ON [dbo].[rxqScriptTransaction] ([DateDispensedSQL]) INCLUDE ([ScriptNumber], [RefillNumber], [Agency], [Copay], [DaysSupply], [DrugId], [QuantityDispensed], [RequestedACQ], [RxpIndicator], [StoreNumber], [Tax], [Total], [PosPickupDateTime], [EstimatedDirFee], [eVoucherAmount], [WholesalerRebateAmount]);
CREATE INDEX [IX_rxqScriptTransaction_AppointmentBookingId] ON [dbo].[rxqScriptTransaction] ([AppointmentBookingId]) INCLUDE ([ScriptNumber], [RefillNumber], [LastModified]);
CREATE INDEX [IX_rxqScriptTransaction_BinId] ON [dbo].[rxqScriptTransaction] ([BinId]);
CREATE INDEX [IX_rxqScriptTransaction_cScriptTransactionId_ScriptNumber] ON [dbo].[rxqScriptTransaction] ([cScriptTransactionId]) INCLUDE ([ScriptNumber]);
CREATE INDEX [IX_rxqScriptTransactionPackingList] ON [dbo].[rxqScriptTransaction] ([PackingListNumber]);
CREATE INDEX [IX_rxtRxReport_StoreQty_Incls] ON [dbo].[rxqScriptTransaction] ([StoreNumber], [QuantityDispensed]) INCLUDE ([ScriptNumber], [RefillNumber], [ChargeCode], [DrugId], [NursingHome], [PriceFormula], [PosPickupDateTime], [cQueueId], [TimeStampComputerDateTime], [PartialFill]);
CREATE INDEX [IX_ScriptTransaction_Agency] ON [dbo].[rxqScriptTransaction] ([Agency]);
CREATE INDEX [IX_ScriptTransaction_DateDispensedSQL] ON [dbo].[rxqScriptTransaction] ([DateDispensedSQL]) INCLUDE ([ScriptNumber], [RefillNumber]);
CREATE INDEX [IX_ScriptTransaction_DateDispensedSQL_Included] ON [dbo].[rxqScriptTransaction] ([DateDispensedSQL]) INCLUDE ([ScriptNumber], [RefillNumber], [Agency], [DaysSupply], [DrugId], [QuantityDispensed], [RequestedACQ], [RxpIndicator], [StoreNumber], [Tax], [Copay], [Total]);
CREATE INDEX [IX_ScriptTransaction_DrugId_DateDispensedSQLInclude] ON [dbo].[rxqScriptTransaction] ([DrugId], [DateDispensedSQL]) INCLUDE ([QuantityDispensed], [StoreNumber]);
CREATE INDEX [IX_ScriptTransaction_HasProblem] ON [dbo].[rxqScriptTransaction] ([HasProblem]);
CREATE INDEX [IX_ScriptTransaction_WaitingBin] ON [dbo].[rxqScriptTransaction] ([ScriptNumber], [RefillNumber], [StoreNumber], [DateDispensedSQL], [Agency], [WorkflowLocation], [DrugId], [PosPickupDateTime], [PosScanFlag]) INCLUDE ([Copay], [CountedByUser], [DaysSupply], [LotNumber], [NCPDCDispensingFee], [NCPDCIngredientCost], [OtherCoverageCode], [PriceFormula], [QuantityDispensed], [RequestedACQ], [RphInitials], [RxpIndicator], [Tax], [Total], [WorkFlowStatus], [PackingListNumber], [cQueueId], [PromiseDateTime], [WorkQueueNote], [Printed], [PartialFill], [eVoucherAmount], [WholesalerRebateAmount], [Source], [PartialPaymentType], [PickupPreference], [CentralFillServiceFee], [BinId]);
CREATE INDEX [IX_ScriptTransactionWorkflowStatus] ON [dbo].[rxqScriptTransaction] ([WorkflowLocation], [DateDispensedSQL]);
CREATE INDEX [IX_TimeStampComputerDateTime] ON [dbo].[rxqScriptTransaction] ([TimeStampComputerDateTime]);
CREATE INDEX [LibertyAuto_17_16_rxqScriptTransaction] ON [dbo].[rxqScriptTransaction] ([DateDispensedSQL]) INCLUDE ([ScriptNumber], [RefillNumber], [Agency], [DaysSupply], [DrugId], [QuantityDispensed], [RequestedACQ], [RxpIndicator], [StoreNumber], [Tax], [PosPickupDateTime]);
CREATE INDEX [LibertyAuto_7_6_rxqScriptTransaction] ON [dbo].[rxqScriptTransaction] ([DateDispensedSQL]) INCLUDE ([ScriptNumber], [RefillNumber], [Agency], [Copay], [DrugId], [RequestedACQ], [RequestedTax], [RxpIndicator], [Total], [eVoucherAmount]);
CREATE INDEX [missing_index_19_18_rxqScriptTransaction] ON [dbo].[rxqScriptTransaction] ([WorkFlowStatus], [DateDispensedSQL], [HasProblem]) INCLUDE ([ScriptNumber], [RefillNumber], [Agency], [Copay], [CountedByUser], [DrugId], [LoggedInUser], [LotNumber], [NCPDCDispensingFee], [NCPDCIngredientCost], [PosScanFlag], [PriceFormula], [PrimaryRejectedFlag], [QuantityDispensed], [RequestedACQ], [RphInitials], [RxpIndicator], [Tax], [Total], [PackingListNumber], [WorkflowLocation], [cQueueId], [PromiseDateTime], [PickupTimeType], [WorkQueueNote], [PrintLabelDateTime], [Printed], [TimeStampComputerDateTime], [PartialFill], [eVoucherAmount], [WholesalerRebateAmount], [Source], [PartialPaymentType], [PatientWaiting]);
CREATE INDEX [missing_index_2_1_rxqScriptTransaction] ON [dbo].[rxqScriptTransaction] ([HasProblem]) INCLUDE ([ScriptNumber], [RefillNumber]);
