-- rxqScriptPayments   (0 rows, 62 columns)
-- Source: RXQRXCOMPOUNDSTORE (Liberty). Read-only reference DDL, synthesized from catalog metadata.
CREATE TABLE [dbo].[rxqScriptPayments] (
    [cScriptPaymentsId] int IDENTITY NOT NULL,
    [ScriptNumber] int NOT NULL,
    [RefillNumber] int NOT NULL,
    [SequenceNumber] int NOT NULL,
    [AgencyCode] varchar(50) NULL,
    [ChargeCode] varchar(50) NULL,
    [ResponseCode] varchar(50) NULL,
    [AuthorizationNumber] varchar(50) NULL,
    [CustomerPayAmount] float NULL,
    [IngredientCostPaid] float NULL,
    [ContractFeePaid] float NULL,
    [SalesTaxPaid] float NULL,
    [TotalAmountPaid] float NULL,
    [RejectCodeCount] int NULL,
    [RejectCodes1] varchar(50) NULL,
    [RejectCodes2] varchar(50) NULL,
    [RejectCodes3] varchar(50) NULL,
    [RejectCodes4] varchar(50) NULL,
    [RejectCodes5] varchar(50) NULL,
    [RejectCodes6] varchar(50) NULL,
    [RejectCodes7] varchar(50) NULL,
    [RejectCodes8] varchar(50) NULL,
    [RejectCodes9] varchar(50) NULL,
    [RejectCodes10] varchar(50) NULL,
    [RejectCodes11] varchar(50) NULL,
    [RejectCodes12] varchar(50) NULL,
    [RejectCodes13] varchar(50) NULL,
    [RejectCodes14] varchar(50) NULL,
    [RejectCodes15] varchar(50) NULL,
    [RejectCodes16] varchar(50) NULL,
    [RejectCodes17] varchar(50) NULL,
    [RejectCodes18] varchar(50) NULL,
    [RejectCodes19] varchar(50) NULL,
    [RejectCodes20] varchar(50) NULL,
    [RxpAnotherIndicator] varchar(50) NULL,
    [CouponType] varchar(50) NULL,
    [CouponNumber] varchar(50) NULL,
    [CouponAmount] float NULL,
    [AgencyPaidSwitch] varchar(50) NULL,
    [PriorAuthorizationType] varchar(50) NULL,
    [PriorAuthorization] varchar(50) NULL,
    [OtherCoverageCode] varchar(50) NULL,
    [EligibilityClarification] varchar(50) NULL,
    [DenialClarification] varchar(50) NULL,
    [PCN] varchar(50) NULL,
    [PaidYYYYMMDD] varchar(50) NULL,
    [OtherPayorId] varchar(50) NULL,
    [LastModified] datetime NULL,
    [IsValid] bit NULL,
    [NCPDPResponsePricingSegment] varbinary(max) NULL,
    [NCPDPSubmissionClarificationCodes] varchar(50) NULL,
    [OverridePrimaryType] varchar(50) NULL,
    [OverridePrimaryPayment] decimal(9,2) NULL,
    [OverridePrimaryCopay] decimal(9,2) NULL,
    [OverridePrimaryRejectCode1] varchar(50) NULL,
    [OverridePrimaryRejectCode2] varchar(50) NULL,
    [OverridePrimaryRejectCode3] varchar(50) NULL,
    [OverridePrimaryRejectCode4] varchar(50) NULL,
    [OverridePrimaryRejectCode5] varchar(50) NULL,
    [AgencySequence] int NULL,
    [eVoucherAmount] decimal(9,2) NULL,
    [PatientThirdPartyId] int NULL,
    CONSTRAINT [PK_rxqScriptPayments] PRIMARY KEY ([ScriptNumber], [RefillNumber], [SequenceNumber])
);

-- Indexes
CREATE INDEX [_dta_index_rxqScriptPayments_195_462624691__K4_K3_K2_K60_K5_7_9_13_42_45_61] ON [dbo].[rxqScriptPayments] ([SequenceNumber], [RefillNumber], [ScriptNumber], [AgencySequence], [AgencyCode]) INCLUDE ([ResponseCode], [CustomerPayAmount], [TotalAmountPaid], [OtherCoverageCode], [PCN], [eVoucherAmount]);
CREATE INDEX [_dta_index_rxqScriptPayments_195_462624691__K4_K60_K5_2_3] ON [dbo].[rxqScriptPayments] ([SequenceNumber], [AgencySequence], [AgencyCode]) INCLUDE ([ScriptNumber], [RefillNumber]);
CREATE INDEX [_dta_index_rxqScriptPayments_36_462624691__K4_K2_K3_K5_K60] ON [dbo].[rxqScriptPayments] ([SequenceNumber], [ScriptNumber], [RefillNumber], [AgencyCode], [AgencySequence]);
CREATE INDEX [IX_ScriptPayment_ScriptNumberRefillNumber] ON [dbo].[rxqScriptPayments] ([ScriptNumber], [RefillNumber]) INCLUDE ([CustomerPayAmount], [TotalAmountPaid], [AgencyCode]);
