-- rxqUser   (134 rows, 50 columns)
-- Source: RXQRXCOMPOUNDSTORE (Liberty). Read-only reference DDL, synthesized from catalog metadata.
CREATE TABLE [dbo].[rxqUser] (
    [cUserId] int IDENTITY NOT NULL,
    [RecordId] varchar(50) NOT NULL,
    [EncryptedPassword] varchar(50) NULL,
    [LastLoginDate] datetime NULL,
    [FirstName] varchar(50) NULL,
    [LastName] varchar(50) NULL,
    [RphInitials] varchar(50) NULL,
    [PrevEncryptedPassword1] varchar(50) NULL,
    [PrevEncryptedPassword2] varchar(50) NULL,
    [PrevEncryptedPassword3] varchar(50) NULL,
    [PrevEncryptedPassword4] varchar(50) NULL,
    [PasswordChanged] date NULL,
    [LockOut] datetime NULL,
    [LockOutCount] int NULL,
    [PasswordRequired] varchar(50) NULL,
    [TimeOutMinutes] int NULL,
    [CashierInitials] varchar(50) NULL,
    [MASTERRECORDID] varchar(50) NULL,
    [LastModified] datetime NULL,
    [IsValid] bit NULL,
    [PIN] varchar(50) NULL,
    [Email] varchar(50) NULL,
    [MobilePhone] varchar(50) NULL,
    [HomePhone] varchar(50) NULL,
    [Title] varchar(50) NULL,
    [MyTheme] varchar(50) NULL,
    [UserImage] varbinary(max) NULL,
    [BirthDate] datetime NULL,
    [HireDate] datetime NULL,
    [ForcePasswordChange] bit NOT NULL,
    [WindowsAD] varchar(256) NULL,
    [LoggableStores] varchar(50) NULL,
    [PromptForClockIn] bit NULL,
    [LibertyId] varchar(50) NULL,
    [NewUser] bit NULL,
    [UserColor] int NULL,
    [ReleaseNotesLastCheckedRxqVersion] varchar(50) NULL,
    [PhoneExtension] varchar(20) NULL,
    [GlobalUserId] uniqueidentifier NULL,
    [AccountLocked] bit NULL,
    [AccountDisabled] bit NULL,
    [LastChecked] datetime NULL,
    [EscriptDefaultView] int NULL,
    [VerificationDefaultView] int NULL,
    [PWEnrollee] bit NOT NULL,
    [HashedPassword] nvarchar(max) NULL,
    [PrevHashedPassword1] nvarchar(max) NULL,
    [PrevHashedPassword2] nvarchar(max) NULL,
    [PrevHashedPassword3] nvarchar(max) NULL,
    [PrevHashedPassword4] nvarchar(max) NULL,
    CONSTRAINT [PK_rxqUser] PRIMARY KEY ([RecordId])
);
